const suggestions = {
  NON_GEO_LOCATION: [
    "Arcade",
    "Army Base",
    "Art Gallery",
    "Baseball Diamond",
    "Bat Cave",
    "Behind a Waterfall",
    "Brewery",
    "Car Wash",
    "Circus",
    "Clock Tower",
    "Cow Pasture",
    "Cyber Space",
    "Double Decker Bus",
    "Dungeon",
    "Elephant Graveyard",
    "Emergency Room",
    "Fire Station",
    "Gas Station",
    "Ghost Town",
    "Heaven",
    "Helicopter",
    "Jazz Club",
    "Junkyard",
    "Kick Boxing Studio",
    "Lost City",
    "Marina",
    "Meat Packing Plant",
    "No Man's Land",
    "An Oasis",
    "Ocean Floor",
    "Oil Rig",
    "Orchestra Pit",
    "Pier",
    "Pirate Ship",
    "Police Station",
    "Quick Sand Pit",
    "Rain Forrest",
    "Recording Studio",
    "The Red Carpet",
    "Roller Rink",
    "Shooting Range",
    "Slaughter House",
    "Space Station",
    "Submarine",
    "Super Market",
    "Swamp",
    "Sweat Shop",
    "Tree House",
    "University",
    "A Villa",
    "Veranda",
    "Vineyard",
    "Wildlife Reserve",
    "Food court at closing time",
    "In a cherry picker working on a power line",
    "Sweat shop break room",
    "Underground militia bunker",
    "Panic room",
    "Dermatologist waiting room",
    "At the edge of a volcano on the summer solstice",
    "Double decker tour bus at the car wash",
    "The backseat of a fancy classic car",
    "Saturday school detention in the library with Judd Nelson",
    "The Oval Office!",
    "Private jet cockpit",
    "Exclusive VIP art gallery opening",
    "Popcorn museum",
    "Stand up comic condominium",
    "Singles bar on a cruise ship",
    "Karaoke bar",
    "Sushi bar",
    "Oxygen bar",
    "Dive bar",
    "Diving board (high)",
    "Diving board (low)",
    "Front porch of a stately southern mansion",
    "Zombie convention",
    "Lactation room",
    "The bathroom at the Oscars",
    "The bathroom at the Pulitzer Prize dinner",
    "The bathroom at a Pink Floyd concert",
    "Bill Cosby’s sweater closet (but Bill is out of town or something)",
    "MC Escher’s back yard",
    "Two-person submarine",
    "Two people making subs",
    "Jigsaw puzzle national championships",
    "Meth lab",
    "Under the bleachers with Amanda",
    "Amanda’s Trans-Am",
    "Amanda’s softball game",
    "Amanda’s driveway",
    "Amanda’s stupid second floor bedroom (night)",
    "A tree branch across the street",
    "Amanda’s bedroom",
    "Dave & Busters",
    "International Space Station’s intercourse pod",
    "Denver",
    "Stratford-on-Avon",
    "Cumberbatch-on-Thames",
    "Wilmington-on-Butterball",
    "Girl-on-Girl",
    "Herkowitz-on-Rye",
    "Makeup trailer on the set of the next big Hollywood blockbuster",
    "Above-ground pool",
    "The only water park in the Middle East",
    "Chinese restaurant on Christmas Day (!!!!)",
    "The utility closet of a Best Western",
    "DOW Chemicals processing facility (Michigan, I’m guessing)",
    "Basement man cave",
    "Stripper pole manufacturing plant",
    "Any garden",
    "Rollerblade park",
    "Deodorant testing lab",
    "Andy Rooney’s breakfast nook",
    "Gun show coat check",
    "The anteroom of a building that has anterooms",
    "The little train at the zoo",
    "Hell",
    "Heaven"
  ],
  EMOTION: [
    "Joyful",
    "Tenderness",
    "Helpless",
    "Defeated",
    "Rageful",
    "Cheerful",
    "Sympathy",
    "Powerless",
    "Bored",
    "Outraged",
    "Content",
    "Adoration",
    "Dreading",
    "Rejected",
    "Hostile",
    "Proud",
    "Fondness",
    "Distrusting",
    "Disillusioned",
    "Bitter",
    "Satisfied",
    "Receptive",
    "Suspicious",
    "Inferior",
    "Hateful",
    "Excited",
    "Interested",
    "Cautious",
    "Confused",
    "Scornful",
    "Amused",
    "Delighted",
    "Disturbed",
    "Grief-stricken",
    "Spiteful",
    "Elated",
    "Shocked",
    "Overwhelmed",
    "Helpless",
    "Vengeful",
    "Enthusiastic",
    "Exhilarated",
    "Uncomfortable",
    "Isolated",
    "Disliked",
    "Optimistic",
    "Dismayed",
    "Guilty",
    "Numb",
    "Resentful",
    "Elated",
    "Amazed",
    "Hurt",
    "Regretful",
    "Trusting",
    "Delighted",
    "Confused",
    "Lonely",
    "Ambivalent",
    "Alienated",
    "Calm",
    "Stunned",
    "Melancholy",
    "Exhausted",
    "Bitter",
    "Relaxed",
    "Interested",
    "Depressed",
    "Insecure",
    "Insulted",
    "Relieved",
    "Intrigued",
    "Hopeless",
    "Disgusted",
    "Indifferent",
    "Hopeful",
    "Absorbed",
    "Sad",
    "Pity",
    "Pleased",
    "Curious",
    "Guilty",
    "Revulsion",
    "Confident",
    "Anticipating",
    "Hurt",
    "Contempt",
    "Brave",
    "Eager",
    "Lonely",
    "Weary",
    "Comfortable",
    "Hesitant",
    "Regretful",
    "Bored",
    "Safe",
    "Fearful",
    "Depressed",
    "Preoccupied",
    "Happy",
    "Anxious",
    "Hopeless",
    "Angry",
    "Love",
    "Worried",
    "Sorrow",
    "Jealous",
    "Lust",
    "Scared",
    "Uncertain",
    "Envious",
    "Aroused",
    "Insecure",
    "Anguished",
    "Annoyed",
    "Tender",
    "Rejected",
    "Disappointed",
    "Humiliated",
    "Compassionate",
    "Horrified",
    "Self conscious",
    "Irritated",
    "Caring",
    "Alarmed",
    "Shamed",
    "Aggravated",
    "Infatuated",
    "Shocked",
    "Embarrassed",
    "Restless",
    "Concern",
    "Panicked",
    "Humiliated",
    "Grumpy",
    "Trust",
    "Afraid",
    "Disgraced",
    "Awkward",
    "Liking",
    "Nervous",
    "Uncomfortable",
    "Exasperated",
    "Attraction",
    "Disoriented",
    "Neglected",
    "Frustrated"
  ],
  ANYTHING: [
    "appendix",
    "grow",
    "word",
    "traffic",
    "shake",
    "serious",
    "soil",
    "reporter",
    "computer",
    "pin",
    "chicken",
    "dentist",
    "annual",
    "future",
    "essential",
    "romantic",
    "nomination",
    "basket",
    "skate",
    "bat",
    "time",
    "runner",
    "polite",
    "bank",
    "work out",
    "colon",
    "winter",
    "tree",
    "dangerous",
    "charm",
    "restrain",
    "nail",
    "freighter",
    "TRUE",
    "fraction",
    "gift",
    "beneficiary",
    "home",
    "retired",
    "lack",
    "obese",
    "day",
    "punch",
    "projection",
    "patient",
    "merit",
    "gap",
    "fraud",
    "prize",
    "large",
    "toast",
    "love",
    "touch",
    "listen",
    "ample",
    "stream",
    "tooth",
    "artist",
    "celebration",
    "sniff",
    "acceptance",
    "overlook",
    "benefit",
    "stain",
    "discriminate",
    "sum",
    "fail",
    "bird",
    "harm",
    "dragon",
    "conventional",
    "miserable",
    "smart",
    "radical",
    "waterfall",
    "snarl",
    "grief",
    "allow",
    "finance",
    "pick",
    "poetry",
    "weapon",
    "ballet",
    "environmental",
    "wine",
    "mosquito",
    "crowd",
    "fitness",
    "habit",
    "duke",
    "care",
    "therapist",
    "goat",
    "reinforce",
    "store",
    "momentum",
    "jealous",
    "revoke",
    "page",
    "summer",
    "orgy",
    "double",
    "restoration",
    "sea",
    "outline",
    "arch",
    "frank",
    "net",
    "class",
    "persist",
    "edge",
    "instinct",
    "wife",
    "bloodshed",
    "break",
    "room",
    "consideration",
    "request",
    "tire",
    "safe",
    "tolerate",
    "mask",
    "initial",
    "morsel",
    "criminal",
    "outside",
    "episode",
    "sofa",
    "kill",
    "lover",
    "fuel",
    "teenager",
    "comfort",
    "outlook",
    "sympathetic",
    "alarm",
    "place",
    "twilight",
    "mistreat",
    "decade",
    "abortion",
    "withdraw",
    "seat",
    "firm",
    "remind",
    "pattern",
    "sand",
    "hook",
    "shock",
    "beer",
    "theory",
    "exploit",
    "marine",
    "great",
    "dance",
    "abundant",
    "scenario",
    "hot",
    "chocolate",
    "drain",
    "corner",
    "garbage",
    "week",
    "exemption",
    "spectrum",
    "ward",
    "power",
    "tie",
    "piano",
    "arrest",
    "school",
    "specimen",
    "coast",
    "outlet",
    "collection",
    "need",
    "siege",
    "branch",
    "paralyzed",
    "elephant",
    "crevice",
    "index",
    "ally",
    "bridge",
    "smooth",
    "dialogue",
    "agree",
    "lift",
    "clear",
    "frozen",
    "snuggle",
    "inquiry",
    "desk",
    "compact",
    "rotten",
    "hostility",
    "cook",
    "deputy",
    "litigation",
    "shy",
    "lounge",
    "chalk",
    "dough",
    "facade",
    "consumption",
    "debut",
    "sleep",
    "qualified",
    "regular",
    "innocent",
    "string",
    "waist",
    "biology",
    "disgrace",
    "permanent",
    "damage",
    "wage",
    "price",
    "union",
    "treasurer",
    "modernize",
    "divorce",
    "attract",
    "butterfly",
    "spokesperson",
    "stool",
    "housing",
    "quit",
    "cancer",
    "privacy",
    "invisible",
    "absent",
    "whisper",
    "tease",
    "amputate",
    "quantity",
    "fate",
    "stomach",
    "plan",
    "source",
    "aid",
    "hemisphere",
    "colony",
    "cottage",
    "belt",
    "loss",
    "swallow",
    "trait",
    "reader",
    "bench",
    "sink",
    "workshop",
    "chance",
    "fork",
    "graze",
    "honor",
    "moment",
    "epicalyx",
    "temptation",
    "reject",
    "snake",
    "side",
    "deviation",
    "address",
    "contempt",
    "appoint",
    "material",
    "fun",
    "hang",
    "jockey",
    "literature",
    "precede",
    "sell",
    "lay",
    "reptile",
    "economic",
    "chaos",
    "snap",
    "physics",
    "carry",
    "variable",
    "short",
    "mess",
    "diet",
    "undress",
    "differ",
    "misery",
    "snack",
    "strip",
    "charismatic",
    "fee",
    "machinery",
    "glare",
    "exhibition",
    "reason",
    "damn",
    "childish",
    "copy",
    "feast",
    "grant"
  ]
}

exports.getRandom = (category) => {
  const chosenCategory = suggestions[category] ? suggestions[category] : suggestions['ANYTHING'];
  return chosenCategory[Math.floor(Math.random() * (chosenCategory.length - 1))];
}
